### ISSUE TITLE
No aarch64 linux wheels are available

### ISSUE THREAD

**Issue by callado4** [wseaton/sqloxide#108]
When trying to install the library on a docker container (python:3.8) running on an M1 Mac, the install fails.  Looking at pypi I don't see any `*linux_aarch64.whl` files - I was able to build one running some of the scripts in build-wheel.sh but I'm not sure yet how to use that file in my own docker container (especially when trying to add the library via poetry).

**Comment by wseaton** [comment]
@callado4 I don't have access to an M1 Mac machine to do builds on, would happily add support for this if it could be done via github actions, but I think we are blocked by: https://github.com/actions/virtual-environments/issues/2187

**Comment by wseaton** [comment]
Actually sorry, looks like you are requesting just a different target linux architecture and not an actual M1 native build since you are running via docker on darwin. I think this is possible to support via a multi-arch build, but I'll have to dig into this when I have free time.

**Comment by kakoni** [comment]
Hi @wseaton! Perhaps using qemu + [cibuildwheel](https://github.com/pypa/cibuildwheel/) could be an easy solution?

**Comment by yuval-illumex** [comment]
Hi @wseaton ,
I have a dev script that build a docker container of my app, and it fails on mac m1 (and works on ubuntu).
Simple Docker build and try to install sqloxide.

What can I do to help with one?

**Comment by piyushdatazip** [comment]
@wseaton I checked https://github.com/pypa/cibuildwheel, they support building python package for ARM64. Can we use this here?

**Comment by kush87** [comment]
Any update on this? Apache superset seems to be using this package and i am stuck here as i cannot build a custom docker image without sqloxide providing arm support.

I know you all are very busy, just want an estimate of timeline as to by when would this be possible.

Once again, very thankful for all that you do.
Thanks.

**Comment by tomtom215** [comment]
Facing the same issue using Superset custom docker image due to Mac M1 linux/arm64/v8 architecture

**Comment by wseaton** [comment]
If you are an arm user and have the rust toolchain installed and install `sqloxide` from git, you should be able to build the .whl you need locally (poetry should hook setuptools-rust), then just copy it into your container image. Basically the same thing that `connectorx` does: https://sfu-db.github.io/connector-x/install.html#build-from-source-code

Until Github Actions has support for arm build environments I can't provide wheels myself, as this is a spare time project. Contributions to the CI are welcome.

Also, while it's cool to see `superset` using this package to speed up database migrations, it is less cool to have users drawn here specifically for M1 support, especially since AFAIK it's an optional dependency.

**Comment by Mokto** [comment]
"sqloxide-fork == 0.1.51" is built on sqoxide 0.1.47
If you're interested in compatible wheels.

**Comment by Mokto** [comment]
See https://github.com/wseaton/sqloxide/pull/263

**Comment by Mokto** [comment]
Now available in sqloxide 0.1.48
